version: '3.7'

services:
  order:
    container_name: order
    build:
      context: .
      args:
        - SERVICE=order
    ports:
      -8420:8420
  price:
    container_name: price 
    build:
      context: .
      args:
        - SERVICE=price
    # ports:
    #   -
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes

  rabbit:
    container_name: rabbit
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5672" ]
      interval: 30s
      timeout: 10s
      retries: 5